name: White Paper
markdown: kramdown
kramdown:
    input: GFM
url: http://makefiletutorial.com
description: Makefile Tutorial by Example
syntax-highlighting:
    enabled: true
    css: syntax.css
highlighter: pygments

# Owner/author information
owner:
  name: Chase Lambert

